---
# Defines tasks to install, secure, and configure Redis

- name: Include the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - redis

- name: Add PPA repository for stable Redis
  apt_repository: >
    repo='ppa:chris-lea/redis-server'
  when: ansible_os_family == 'Debian'
  tags:
    - redis

- name: Install packages for Debian derivatives
  apt: >
    pkg={{ item }}
    update_cache=yes
    state=latest
  with_items: redis_packages
  when: ansible_os_family == 'Debian'
  tags:
    - redis

- name: Ensure Redis configuration directory
  file: >
    path={{ redis_config_dir }}/conf.d
    mode=0755 owner=root group=root
    state=directory
  tags:
    - redis

- name: Write Redis configuration templates
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0644 owner=root group=root
    backup=yes
  with_items:
      - { src: "redis-conf.j2",
          dest: "{{ redis_config_dir }}/redis.conf" }
      - { src: "conf-d-local-conf.j2",
          dest: "{{ redis_config_dir }}/conf.d/local.conf" }
  notify:
    - restart redis
  tags:
    - redis

- name: Write log rotation template
  template: >
    src=logrotate-d-redis.j2
    dest=/etc/logrotate.d/redis
    mode=0644 owner=root group=root
    backup=yes
  tags:
    - redis

- name: Set the kernel paramter for VM overcommit
  sysctl: >
    name="vm.overcommit_memory"
    value=1
    state=present
  tags:
    - redis

- name: Start Redis on server boot
  service: >
    name={{ redis_service }}
    enabled=yes
    state=started
  tags:
    - redis
