---
# Handlers for Redis notifications.

- name: stop redis
  service: >
    name={{ redis_service }}
    state=stopped

- name: start redis
  service: >
    name={{ redis_service }}
    state=started
    enabled=yes

- name: restart redis
  service: >
    name={{ redis_service }}
    state=restarted
    enabled=yes
